schema_version = "1.0.0"
id = "uma_addon"
version = "2.6.0"
name = "UMA Addon"
tagline = "Streamline the workflow for umamusume models"
maintainer = "小微在线上"
type = "add-on"
license = ["SPDX:GPL-3.0-or-later"]
blender_version_min = "4.2.0"
website = "https://www.bilibili.com/opus/1101994702993883141"
python_dependencies = ["Pillow"]
[permissions]
network = "需要联网下载 Python 依赖库 Pillow"
files = "需要读写配置文件与生成狸动画缓存"